Gibz\ElectricBundle\Entity\GameState:
    type: entity
    table: null
    repositoryClass: Gibz\ElectricBundle\Repository\GameStateRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        uniqId:
            type: string
            length: 255
            unique: true
            column: uniq_id
        state:
            type: text
        counter:
            type: integer
    manyToOne:
        user:
            targetEntity: Gibz\ElectricBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
