Gibz\ElectricBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Gibz\ElectricBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
            column: name
    lifecycleCallbacks: {  }
