<?php

namespace Gibz\ElectricBundle\Repository;

/**
 * GameStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameStateRepository extends \Doctrine\ORM\EntityRepository
{
}
